#!/bin/bash

Ny=(5) # 10 20 40 80 160 320 640)
W=(0.6 0.3 0.15 0.075 0.0375 0.01875 0.009375 0.0046875 0.00234375)
D=(0.2 0.1 0.05 0.025 0.0125 0.00625 0.003125 0.0015625 0.00078125)

pRight=(-0.6 -0.3 -0.15 -0.075 -0.0375 -0.01875 -0.009375 -0.0046875 -0.00234375)
endTime=(10.0 10.0 10.0 10.0 10.0 10.0 10.0 40.0 80.0)

caseID=0
# mesh loop
for res in "${Ny[@]}"
do
    # define caseName
    caseName='Ny'"$res"

    # create case 
    cp -r template "$caseName"
    mv  $caseName/system/blockMeshDict.template $caseName/system/blockMeshDict

    # adapt data
    sed -i 's/'"\!\@Ny\@\!"'/'"$res"'/g' "$caseName/system/blockMeshDict" 
    sed -i 's/'"\!\@L\@\!"'/'"${W[caseID]}"'/g' "$caseName/system/blockMeshDict" 
    sed -i 's/'"\!\@D\@\!"'/'"${D[caseID]}"'/g' "$caseName/system/blockMeshDict" 
    sed -i 's/'"\!\@pRight\@\!"'/'"${pRight[caseID]}"'/g' "$caseName/0/p" 
    sed -i 's/'"\!\@endTime\@\!"'/'"${endTime[caseID]}"'/g' "$caseName/system/controlDict" 

    # run case
    echo "Computing case: $caseName"
    # Insert & after ./Allrun to run all cases in parallel and give back control to terminal
    (cd $caseName && ./Allrun )

    ((caseID++))
done
