#!/bin/bash

beta=(0.01) #(0.0 0.000000001 0.00000001 0.0000001 0.000001 0.00001 0.0001 0.001 0.01 0.1 1.0 10.0 100.0)

# beta loop
for betaValue in "${beta[@]}"
do
# replace data
    caseName='slipLength'"$betaValue"
    echo "Running evalNavierSlip in $caseName."

    (cd $caseName && ./Alleval)

done
